import "server-only";

/**
 * Shared booking-token helpers used by the bookings creation route AND the
 * reminder cron route. Single source of truth for the raw-token format and
 * the hashing function.
 *
 * IMPORTANT: This module is a thin facade over `lib/bookings/tokens.ts`
 * (the canonical Phase 5 implementation). We re-export `hashToken` so that
 * tokens generated by the cron route hash to the same value that the
 * existing cancel/reschedule resolvers (`app/cancel/[token]/_lib/...` and
 * `app/reschedule/[token]/_lib/...`) compute when verifying URL tokens.
 *
 * Do NOT switch the hash function (e.g. node:crypto vs Web Crypto) without
 * also updating every caller of `hashToken` — verification depends on a
 * single canonical hex SHA-256 output.
 *
 * Format choice (Plan 08-04):
 *   - Raw token format: crypto.randomUUID() — 122 bits of entropy (RFC 4122 v4),
 *     same as Phase 5 / lib/bookings/tokens.ts. Edge-runtime compatible.
 *   - Hash format: hex-encoded SHA-256 (via Web Crypto subtle.digest) —
 *     re-exported from lib/bookings/tokens.ts.
 */

export { hashToken } from "@/lib/bookings/tokens";

/**
 * Generate a single fresh raw token.
 *
 * Returns a UUID v4 (122 bits of entropy). Same format as the raw tokens
 * created by lib/bookings/tokens.ts#generateBookingTokens — required so
 * cron-rotated tokens look identical to confirmation-email tokens to
 * downstream verification (which only checks the SHA-256 hash, not format).
 */
export function generateRawToken(): string {
  return crypto.randomUUID();
}
